# Generated by Django 5.0.1 on 2024-01-21 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(max_length=250)),
                ('flag', models.URLField()),
                ('country_code', models.CharField(max_length=250)),
                ('csirt', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('web', models.URLField(blank=True, default='None', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Information',
            },
        ),
    ]
