# Generated by Django 5.0.1 on 2024-01-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
                ('flag', models.URLField(editable=False)),
                ('country_code', models.CharField(editable=False, max_length=250)),
                ('csirt', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('web', models.URLField(blank=True, default='None', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Information',
            },
        ),
    ]
